version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=send_it_later
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log

  web:
    image: app/web
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --bind :$PORT --workers 5 --threads 5 main:flask_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
